# -*- coding: utf-8 -*-
"""yt-insights-pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvKbgH7MAIebyvmfktTAa_ttXD5NxSHb
"""

import pandas as pd
import numpy as np
from datetime import datetime

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

import pandas as pd

chart = pd.read_csv("Chart data(1).csv")
table = pd.read_csv("Table data(1).csv")
totals = pd.read_csv("Totals(1).csv")

print(chart.head())
print(table.head())
print(totals.head())

from IPython.display import display

display(chart.head())
display(table.head())
display(totals.head())

print("Chart Shape :", chart.shape)
print("Table Shape :", table.shape)
print("Totals Shape :", totals.shape)

print("\nChart Columns")
print(chart.columns)

print("\nTable Columns")
print(table.columns)

print("\nTotals Columns")
print(totals.columns)

def quality_report(df, name):

    print("="*60)
    print(name)
    print("="*60)

    print("\nShape :", df.shape)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows :", df.duplicated().sum())

    print("\nData Types")
    print(df.dtypes)

quality_report(chart,"Chart")
quality_report(table,"Table")
quality_report(totals,"Totals")

def clean_columns(df):

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("(", "", regex=False)
        .str.replace(")", "", regex=False)
        .str.replace("%", "percent", regex=False)
        .str.replace("-", "_", regex=False)
    )

    return df

chart = clean_columns(chart)
table = clean_columns(table)
totals = clean_columns(totals)

print(table.columns)

chart["date"] = pd.to_datetime(chart["date"], errors="coerce")

table["video_publish_time"] = pd.to_datetime(
    table["video_publish_time"],
    errors="coerce"
)

totals["date"] = pd.to_datetime(
    totals["date"],
    errors="coerce"
)

chart.drop_duplicates(inplace=True)
table.drop_duplicates(inplace=True)
totals.drop_duplicates(inplace=True)

for df in [chart, table, totals]:

    num = df.select_dtypes(include="number").columns

    df[num] = df[num].fillna(df[num].median())

    cat = df.select_dtypes(include="object").columns

    df[cat] = df[cat].fillna("Unknown")

import sqlite3

# Create Database
conn = sqlite3.connect("yt_insights.db")

print("✅ Database Created Successfully")

chart.to_sql(
    "daily_watchtime",
    conn,
    if_exists="replace",
    index=False
)

table.to_sql(
    "videos",
    conn,
    if_exists="replace",
    index=False
)

totals.to_sql(
    "daily_totals",
    conn,
    if_exists="replace",
    index=False
)

print("✅ Tables Created Successfully")

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

query = """

SELECT
video_title,
views

FROM videos

ORDER BY views DESC

LIMIT 10

"""

pd.read_sql(query, conn)

query = """

SELECT

video_title,

impressions_click_through_rate_percent AS CTR,

views

FROM videos

ORDER BY CTR DESC

LIMIT 10

"""

pd.read_sql(query, conn)

query = """

SELECT

video_title,

watch_time_hours

FROM videos

ORDER BY watch_time_hours DESC

LIMIT 10

"""

pd.read_sql(query, conn)

query = """

SELECT

video_title,

views,

RANK()

OVER(

ORDER BY views DESC

)

AS Rank_No

FROM videos

LIMIT 20

"""

pd.read_sql(query, conn)

query = """

SELECT

video_title,

views,

ROW_NUMBER()

OVER(

ORDER BY views DESC

)

AS Row_No

FROM videos

LIMIT 20

"""

pd.read_sql(query, conn)

query = """

SELECT

performance_tier,

COUNT(*) AS Total_Videos

FROM videos

GROUP BY performance_tier

"""

pd.read_sql(query, conn)

table.columns

# Performance Tier Create

q75 = table["views"].quantile(0.75)
q25 = table["views"].quantile(0.25)

def performance(v):
    if v >= q75:
        return "Top"
    elif v >= q25:
        return "Mid"
    else:
        return "Low"

table["performance_tier"] = table["views"].apply(performance)

print("✅ Performance Tier Created")

table.columns

table.to_sql(
    "videos",
    conn,
    if_exists="replace",
    index=False
)

print("✅ SQL Table Updated")

query = """
SELECT
    performance_tier,
    COUNT(*) AS Total_Videos
FROM videos
GROUP BY performance_tier
"""

pd.read_sql(query, conn)

!pip install openpyxl xlsxwriter

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.chart import BarChart, Reference
from openpyxl.utils import get_column_letter

# Create Excel File

with pd.ExcelWriter("YT_Analytics_Report.xlsx", engine="openpyxl") as writer:

    table.to_excel(writer,
                   sheet_name="Video Performance",
                   index=False)

    chart.to_excel(writer,
                   sheet_name="Daily Watchtime",
                   index=False)

    totals.to_excel(writer,
                    sheet_name="Daily Totals",
                    index=False)

wb = load_workbook("YT_Analytics_Report.xlsx")

summary = wb.create_sheet("Executive Summary")

summary["A1"] = "YT INSIGHTS PRO"

summary["A1"].font = Font(size=22,bold=True)

summary["A1"].fill = PatternFill(
    fill_type="solid",
    fgColor="1F4E78"
)

summary["A1"].alignment = Alignment(horizontal="center")

summary.merge_cells("A1:D1")

summary["A3"] = "Total Views"
summary["B3"] = table["views"].sum()

summary["A4"] = "Total Watch Hours"
summary["B4"] = round(table["watch_time_hours"].sum(),2)

summary["A5"] = "Average CTR"
summary["B5"] = round(
    table["impressions_click_through_rate_percent"].mean(),2
)

summary["A6"] = "Total Subscribers"

summary["B6"] = table["subscribers"].sum()

top20 = table.sort_values(
    "views",
    ascending=False
).head(20)

if "Top Videos" in wb.sheetnames:
    del wb["Top Videos"]

ws = wb.create_sheet("Top Videos")

for r in top20.itertuples(index=False):
    ws.append(r)

for cell in ws[1]:
    cell.font = Font(bold=True)

for sheet in wb.sheetnames:

    ws = wb[sheet]

    for column in ws.columns:

        length = max(
            len(str(cell.value))
            if cell.value else 0
            for cell in column
        )

        ws.column_dimensions[
            get_column_letter(column[0].column)
        ].width = length + 3

ws = wb["Top Videos"]

chart_bar = BarChart()

data = Reference(
    ws,
    min_col=10,
    min_row=2,
    max_row=21
)

cats = Reference(
    ws,
    min_col=2,
    min_row=2,
    max_row=21
)

chart_bar.add_data(data)

chart_bar.set_categories(cats)

chart_bar.title = "Top 20 Videos"

ws.add_chart(chart_bar,"P2")

wb.save("YT_Analytics_Report.xlsx")

print("✅ Excel Report Generated Successfully")

from google.colab import files

files.download("YT_Analytics_Report.xlsx")

!pip install matplotlib seaborn plotly

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

sns.set_style("whitegrid")

plt.rcParams["figure.figsize"]=(12,6)

chart["date"] = pd.to_datetime(chart["date"])
totals["date"] = pd.to_datetime(totals["date"])

plt.figure(figsize=(14,6))

plt.plot(
    totals["date"],
    totals["average_view_duration"],
    linewidth=2
)

plt.title("Daily Average View Duration")

plt.xlabel("Date")

plt.ylabel("Average View Duration")

plt.xticks(rotation=45)

plt.tight_layout()

plt.savefig("01_daily_average_view_duration.png")

plt.show()

top20 = table.sort_values(
    "views",
    ascending=False
).head(20)

plt.figure(figsize=(14,8))

sns.barplot(
    data=top20,
    y="video_title",
    x="views"
)

plt.title("Top 20 Videos By Views")

plt.tight_layout()

plt.savefig("02_top20_videos.png")

plt.show()

plt.figure(figsize=(10,6))

sns.histplot(
    table["views"],
    bins=30,
    kde=True
)

plt.title("Views Distribution")

plt.savefig("03_views_distribution.png")

plt.show()

plt.figure(figsize=(12,7))

sns.scatterplot(
    data=table,
    x="impressions_click_through_rate_percent",
    y="views",
    size="views",
    alpha=0.7
)

plt.title("CTR vs Views")

plt.savefig("04_ctr_vs_views.png")

plt.show()

plt.figure(figsize=(12,5))

sns.boxplot(
    x=table["views"]
)

plt.title("Views Outlier Detection")

plt.savefig("05_boxplot.png")

plt.show()

plt.figure(figsize=(12,6))

sns.histplot(
    table["subscribers"],
    bins=20,
    kde=True
)

plt.title("Subscribers Distribution")

plt.savefig("06_subscribers.png")

plt.show()

numeric = table.select_dtypes(include="number")

plt.figure(figsize=(12,8))

sns.heatmap(
    numeric.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.savefig("07_heatmap.png")

plt.show()

fig = px.line(
    totals,
    x="date",
    y="average_view_duration",
    title="Interactive Average View Duration"
)

fig.show()

fig.write_html("08_interactive_dashboard.html")

from google.colab import files

files.download("01_daily_average_view_duration.png")
files.download("02_top20_videos.png")
files.download("03_views_distribution.png")
files.download("04_ctr_vs_views.png")
files.download("05_boxplot.png")
files.download("06_subscribers.png")
files.download("07_heatmap.png")
files.download("08_interactive_dashboard.html")

!pip install xgboost scikit-learn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

from xgboost import XGBClassifier

import matplotlib.pyplot as plt
import seaborn as sns

# Convert publish date

table["video_publish_time"] = pd.to_datetime(
    table["video_publish_time"],
    errors="coerce"
)

# Publish hour
table["publish_hour"] = table["video_publish_time"].dt.hour.fillna(0)

# Day of week
table["day_of_week"] = table["video_publish_time"].dt.dayofweek.fillna(0)

# Title Length
table["title_length"] = table["video_title"].astype(str).str.len()

# Video Age
today = pd.Timestamp.today()

table["video_age_days"] = (
    today - table["video_publish_time"]
).dt.days.fillna(0)

q75 = table["views"].quantile(0.75)
q25 = table["views"].quantile(0.25)

def performance(v):
    if v >= q75:
        return "Top"
    elif v >= q25:
        return "Mid"
    else:
        return "Low"

table["performance_tier"] = table["views"].apply(performance)

features = [

    "publish_hour",

    "day_of_week",

    "title_length",

    "duration",

    "impressions",

    "impressions_click_through_rate_percent",

    "average_percentage_viewed_percent",

    "stayed_to_watch_percent"

]

X = table[features]

y = table["performance_tier"]

encoder = LabelEncoder()

y = encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42

)

model = XGBClassifier(

    n_estimators=100,

    max_depth=4,

    learning_rate=0.1,

    random_state=42

)

model.fit(X_train,y_train)

pred = model.predict(X_test)

print(classification_report(y_test,pred))

cm = confusion_matrix(y_test,pred)

plt.figure(figsize=(6,5))

sns.heatmap(

    cm,

    annot=True,

    fmt="d",

    cmap="Blues"

)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

importance = pd.DataFrame({

    "Feature":features,

    "Importance":model.feature_importances_

})

importance = importance.sort_values(

    "Importance",

    ascending=False

)

plt.figure(figsize=(10,6))

sns.barplot(

    data=importance,

    x="Importance",

    y="Feature"

)

plt.title("Feature Importance")

plt.show()

table["predicted_tier"] = encoder.inverse_transform(

    model.predict(X)

)

table.head()

table.to_csv(

    "yt_final_dataset.csv",

    index=False

)

print("✅ Final Dataset Saved")

from google.colab import files

files.download("yt_final_dataset.csv")

import pandas as pd

# Ensure datetime
table["video_publish_time"] = pd.to_datetime(table["video_publish_time"])

# Create Month Column
table["month"] = table["video_publish_time"].dt.to_period("M").astype(str)

monthly_summary = table.groupby("month").agg({
    "views":"sum",
    "watch_time_hours":"sum",
    "subscribers":"sum",
    "impressions":"sum"
}).reset_index()

monthly_summary.head()

top_video = table.loc[table["views"].idxmax(),"video_title"]

best_month = monthly_summary.loc[
    monthly_summary["views"].idxmax(),
    "month"
]

kpi = pd.DataFrame({

    "total_views":[table["views"].sum()],

    "total_watch_hours":[table["watch_time_hours"].sum()],

    "total_subscribers":[table["subscribers"].sum()],

    "average_ctr":[
        table["impressions_click_through_rate_percent"].mean()
    ],

    "average_view_duration":[
        table["average_view_duration"].astype(str).count()
    ],

    "best_month":[best_month],

    "top_video":[top_video]

})

kpi

top_videos = table.sort_values(
    "views",
    ascending=False
).head(50)

top_videos.head()

# Convert average_view_duration to timedelta
chart["average_view_duration"] = pd.to_timedelta(
    chart["average_view_duration"],
    errors="coerce"
)

# Convert to seconds
chart["average_view_duration_sec"] = chart["average_view_duration"].dt.total_seconds()

# Daily Summary
daily_summary = chart.groupby("date").agg({
    "average_view_duration_sec": "mean"
}).reset_index()

daily_summary.rename(columns={
    "average_view_duration_sec": "avg_view_duration_sec"
}, inplace=True)

daily_summary.head()

daily_summary["avg_view_duration"] = pd.to_timedelta(
    daily_summary["avg_view_duration_sec"],
    unit="s"
)

table.to_csv("yt_videos_powerbi.csv", index=False)
monthly_summary.to_csv("yt_monthly_summary.csv", index=False)
top_videos.to_csv("yt_top_videos.csv", index=False)
daily_summary.to_csv("yt_daily_summary.csv", index=False)
kpi.to_csv("yt_kpis.csv", index=False)

print("✅ All Power BI Files Exported Successfully")

from google.colab import files

files.download("yt_videos_powerbi.csv")
files.download("yt_monthly_summary.csv")
files.download("yt_top_videos.csv")
files.download("yt_daily_summary.csv")
files.download("yt_kpis.csv")